import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";
import { authTables } from "@convex-dev/auth/server";

export default defineSchema({
  ...authTables,

  organizations: defineTable({
    name: v.string(),
    legalName: v.optional(v.string()),
    legalForm: v.optional(v.string()),
    shareCapital: v.optional(v.string()),
    siren: v.optional(v.string()),
    siret: v.optional(v.string()),
    vatNumber: v.optional(v.string()),
    apeCode: v.optional(v.string()),
    registerNumber: v.optional(v.string()),
    registerCity: v.optional(v.string()),
    email: v.optional(v.string()),
    phone: v.optional(v.string()),
    address: v.optional(v.string()),
    postalCode: v.optional(v.string()),
    city: v.optional(v.string()),
    country: v.optional(v.string()),
    logoUrl: v.optional(v.string()),
    defaultVatRate: v.number(),
    defaultHourlyRate: v.optional(v.number()),
    defaultMarginRate: v.optional(v.number()),
    quotePrefix: v.optional(v.string()),
    invoicePrefix: v.optional(v.string()),
    paymentTermsDays: v.optional(v.number()),
    quoteValidityDays: v.optional(v.number()),
    paymentTermsText: v.optional(v.string()),
    latePenaltyText: v.optional(v.string()),
    discountTermsText: v.optional(v.string()),
    taxExemptionText: v.optional(v.string()),
    quotePricingText: v.optional(v.string()),
    legalNotice: v.optional(v.string()),
    bankDetails: v.optional(v.string()),
    defaultOperationType: v.optional(v.union(v.literal("goods"), v.literal("services"), v.literal("mixed"))),
    taxDebitOption: v.optional(v.boolean()),
    professionalInsurance: v.optional(v.string()),
    mediatorInfo: v.optional(v.string()),
    acceptanceText: v.optional(v.string()),
    accountingClientAccount: v.optional(v.string()),
    accountingBankAccount: v.optional(v.string()),
    accountingVatCollectedAccount: v.optional(v.string()),
    accountingSalesGoodsAccount: v.optional(v.string()),
    accountingSalesServicesAccount: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.optional(v.number()),
  }).index("by_name", ["name"]),

  organizationMembers: defineTable({
    organizationId: v.id("organizations"),
    userId: v.id("users"),
    role: v.union(v.literal("owner"), v.literal("admin"), v.literal("sales"), v.literal("readonly"), v.literal("member")),
    createdAt: v.number(),
    updatedAt: v.optional(v.number()),
  })
    .index("by_userId", ["userId"])
    .index("by_organizationId", ["organizationId"])
    .index("by_organizationId_and_userId", ["organizationId", "userId"]),

  organizationInvitations: defineTable({
    organizationId: v.id("organizations"),
    email: v.string(),
    role: v.union(v.literal("admin"), v.literal("sales"), v.literal("readonly"), v.literal("member")),
    tokenHash: v.string(),
    status: v.union(v.literal("pending"), v.literal("accepted"), v.literal("revoked"), v.literal("expired")),
    invitedByUserId: v.id("users"),
    expiresAt: v.number(),
    acceptedAt: v.optional(v.number()),
    revokedAt: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_tokenHash", ["tokenHash"])
    .index("by_organizationId", ["organizationId"])
    .index("by_organizationId_and_email", ["organizationId", "email"]),

  activityLogs: defineTable({
    organizationId: v.id("organizations"),
    actorUserId: v.optional(v.id("users")),
    actorName: v.optional(v.string()),
    actorEmail: v.optional(v.string()),
    action: v.string(),
    resourceType: v.string(),
    resourceId: v.optional(v.string()),
    summary: v.string(),
    metadata: v.optional(v.string()),
    createdAt: v.number(),
  })
    .index("by_organizationId", ["organizationId"])
    .index("by_organizationId_and_createdAt", ["organizationId", "createdAt"]),

  documentEmailEvents: defineTable({
    organizationId: v.id("organizations"),
    documentKind: v.union(v.literal("quote"), v.literal("invoice")),
    eventKind: v.optional(v.union(v.literal("send"), v.literal("reminder"))),
    quoteId: v.optional(v.id("quotes")),
    invoiceId: v.optional(v.id("invoices")),
    recipient: v.string(),
    senderUserId: v.optional(v.id("users")),
    senderName: v.optional(v.string()),
    senderEmail: v.optional(v.string()),
    createdAt: v.number(),
  })
    .index("by_quoteId_and_createdAt", ["quoteId", "createdAt"])
    .index("by_invoiceId_and_createdAt", ["invoiceId", "createdAt"])
    .index("by_organizationId_and_createdAt", ["organizationId", "createdAt"]),

  documentSequences: defineTable({
    organizationId: v.id("organizations"),
    kind: v.union(v.literal("quotes"), v.literal("invoices")),
    year: v.number(),
    nextNumber: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_organizationId_and_kind_and_year", ["organizationId", "kind", "year"]),

  clients: defineTable({
    organizationId: v.id("organizations"),
    name: v.string(),
    firstName: v.optional(v.string()),
    companyName: v.optional(v.string()),
    customerType: v.optional(v.union(v.literal("individual"), v.literal("business"), v.literal("public"))),
    siren: v.optional(v.string()),
    siret: v.optional(v.string()),
    vatNumber: v.optional(v.string()),
    email: v.optional(v.string()),
    phone: v.optional(v.string()),
    address: v.optional(v.string()),
    postalCode: v.optional(v.string()),
    city: v.optional(v.string()),
    country: v.optional(v.string()),
    notes: v.optional(v.string()),
    active: v.optional(v.boolean()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_organizationId", ["organizationId"]),

  materials: defineTable({
    organizationId: v.id("organizations"),
    name: v.string(),
    reference: v.optional(v.string()),
    category: v.optional(v.string()),
    description: v.optional(v.string()),
    unit: v.union(
      v.literal("piece"),
      v.literal("metre"),
      v.literal("m2"),
      v.literal("m3"),
      v.literal("litre"),
      v.literal("kilogramme"),
      v.literal("lot"),
    ),
    purchasePriceHt: v.number(),
    divisible: v.boolean(),
    quantityPerLot: v.optional(v.number()),
    length: v.optional(v.number()),
    width: v.optional(v.number()),
    height: v.optional(v.number()),
    defaultWasteRate: v.number(),
    supplier: v.optional(v.string()),
    favorite: v.optional(v.boolean()),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_organizationId", ["organizationId"]),

  services: defineTable({
    organizationId: v.id("organizations"),
    name: v.string(),
    description: v.optional(v.string()),
    unit: v.union(v.literal("heure"), v.literal("forfait"), v.literal("jour"), v.literal("m2"), v.literal("metre")),
    unitPriceHt: v.number(),
    favorite: v.optional(v.boolean()),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_organizationId", ["organizationId"]),

  quoteTemplates: defineTable({
    organizationId: v.id("organizations"),
    name: v.string(),
    category: v.optional(v.string()),
    description: v.optional(v.string()),
    favorite: v.optional(v.boolean()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_organizationId", ["organizationId"]),

  quoteTemplateLines: defineTable({
    organizationId: v.id("organizations"),
    templateId: v.id("quoteTemplates"),
    kind: v.union(v.literal("material"), v.literal("service"), v.literal("custom")),
    materialId: v.optional(v.id("materials")),
    serviceId: v.optional(v.id("services")),
    section: v.optional(v.string()),
    description: v.string(),
    unit: v.string(),
    quantity: v.number(),
    unitPriceHt: v.number(),
    wasteRate: v.number(),
    marginRate: v.number(),
    sortOrder: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_organizationId", ["organizationId"])
    .index("by_templateId_and_sortOrder", ["templateId", "sortOrder"]),

  quotes: defineTable({
    organizationId: v.id("organizations"),
    clientId: v.optional(v.id("clients")),
    number: v.string(),
    title: v.string(),
    siteDescription: v.optional(v.string()),
    deliveryAddress: v.optional(v.string()),
    operationType: v.optional(v.union(v.literal("goods"), v.literal("services"), v.literal("mixed"))),
    taxDebitOption: v.optional(v.boolean()),
    status: v.union(
      v.literal("draft"),
      v.literal("sent"),
      v.literal("accepted"),
      v.literal("refused"),
      v.literal("invoiced"),
      v.literal("void"),
    ),
    totalHt: v.number(),
    totalTtc: v.number(),
    vatRate: v.number(),
    issueDate: v.number(),
    validUntil: v.optional(v.number()),
    paymentTermsText: v.optional(v.string()),
    latePenaltyText: v.optional(v.string()),
    legalNotice: v.optional(v.string()),
    notes: v.optional(v.string()),
    convertedInvoiceId: v.optional(v.id("invoices")),
    revisionOfQuoteId: v.optional(v.id("quotes")),
    revisionNumber: v.optional(v.number()),
    supersededByQuoteId: v.optional(v.id("quotes")),
    finalizedAt: v.optional(v.number()),
    publicTokenHash: v.optional(v.string()),
    publicTokenCreatedAt: v.optional(v.number()),
    publicTokenRevokedAt: v.optional(v.number()),
    clientDecision: v.optional(v.union(v.literal("accepted"), v.literal("refused"))),
    clientDecisionAt: v.optional(v.number()),
    clientSignature: v.optional(v.string()),
    clientDecisionIp: v.optional(v.string()),
    clientDecisionUserAgent: v.optional(v.string()),
    sentAt: v.optional(v.number()),
    acceptedAt: v.optional(v.number()),
    refusedAt: v.optional(v.number()),
    invoicedAt: v.optional(v.number()),
    voidedAt: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_organizationId", ["organizationId"])
    .index("by_organizationId_and_clientId", ["organizationId", "clientId"])
    .index("by_organizationId_and_number", ["organizationId", "number"])
    .index("by_publicTokenHash", ["publicTokenHash"]),

  quoteItems: defineTable({
    organizationId: v.id("organizations"),
    quoteId: v.id("quotes"),
    kind: v.union(v.literal("material"), v.literal("service"), v.literal("custom")),
    materialId: v.optional(v.id("materials")),
    serviceId: v.optional(v.id("services")),
    section: v.optional(v.string()),
    description: v.string(),
    unit: v.string(),
    quantity: v.number(),
    unitPriceHt: v.number(),
    wasteRate: v.number(),
    marginRate: v.number(),
    quantityWithWaste: v.optional(v.number()),
    purchasedQuantity: v.optional(v.number()),
    deliveredPhysicalQuantity: v.optional(v.number()),
    wasteQuantity: v.optional(v.number()),
    realCostHt: v.optional(v.number()),
    totalHt: v.number(),
    sortOrder: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_organizationId", ["organizationId"])
    .index("by_quoteId", ["quoteId"])
    .index("by_quoteId_and_sortOrder", ["quoteId", "sortOrder"]),

  invoices: defineTable({
    organizationId: v.id("organizations"),
    quoteId: v.optional(v.id("quotes")),
    clientId: v.optional(v.id("clients")),
    number: v.string(),
    invoiceKind: v.optional(v.union(v.literal("standard"), v.literal("deposit"), v.literal("balance"), v.literal("credit"))),
    creditedInvoiceId: v.optional(v.id("invoices")),
    creditInvoiceId: v.optional(v.id("invoices")),
    depositRate: v.optional(v.number()),
    sourceQuoteTotalHt: v.optional(v.number()),
    sourceQuoteTotalTtc: v.optional(v.number()),
    deductedDepositHt: v.optional(v.number()),
    deductedDepositTtc: v.optional(v.number()),
    deliveryAddress: v.optional(v.string()),
    operationType: v.optional(v.union(v.literal("goods"), v.literal("services"), v.literal("mixed"))),
    taxDebitOption: v.optional(v.boolean()),
    status: v.union(v.literal("draft"), v.literal("sent"), v.literal("partially_paid"), v.literal("paid"), v.literal("overdue"), v.literal("void")),
    totalHt: v.number(),
    totalTtc: v.number(),
    vatRate: v.number(),
    issueDate: v.number(),
    serviceDate: v.optional(v.number()),
    dueDate: v.number(),
    finalizedAt: v.optional(v.number()),
    sentAt: v.optional(v.number()),
    paidAt: v.optional(v.number()),
    voidedAt: v.optional(v.number()),
    paymentMethod: v.optional(v.string()),
    paymentReference: v.optional(v.string()),
    paymentTermsText: v.optional(v.string()),
    latePenaltyText: v.optional(v.string()),
    legalNotice: v.optional(v.string()),
    bankDetails: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_organizationId", ["organizationId"])
    .index("by_organizationId_and_clientId", ["organizationId", "clientId"])
    .index("by_organizationId_and_quoteId", ["organizationId", "quoteId"])
    .index("by_organizationId_and_creditedInvoiceId", ["organizationId", "creditedInvoiceId"])
    .index("by_organizationId_and_number", ["organizationId", "number"]),

  invoicePayments: defineTable({
    organizationId: v.id("organizations"),
    invoiceId: v.id("invoices"),
    amountTtc: v.number(),
    paidAt: v.number(),
    paymentMethod: v.optional(v.string()),
    paymentReference: v.optional(v.string()),
    notes: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_organizationId", ["organizationId"])
    .index("by_invoiceId_and_paidAt", ["invoiceId", "paidAt"]),
});
