sonar.organization=maxenceboo
sonar.projectKey=BooriseBack
sonar.projectName=BooriseBack

sonar.sources=src/main
sonar.tests=src/test
sonar.exclusions=**/target/**,**/build/**
sonar.java.coveragePlugin=jacoco
sonar.junit.reportPaths=target/surefire-reports
sonar.jacoco.reportPaths=target/jacoco.exec
